"""empty message

Revision ID: 3a52c4bbb3c9
Revises: 50c3dbd07dc2
Create Date: 2024-09-01 18:59:11.912850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a52c4bbb3c9'
down_revision = '50c3dbd07dc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('company_logo',
               existing_type=sa.BLOB(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('company_favicon',
               existing_type=sa.BLOB(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('company_favicon',
               existing_type=sa.Text(),
               type_=sa.BLOB(),
               existing_nullable=True)
        batch_op.alter_column('company_logo',
               existing_type=sa.Text(),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
