"""empty message

Revision ID: 4e2691cebb28
Revises: 60afd15551eb
Create Date: 2024-10-27 21:31:49.353435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e2691cebb28'
down_revision = '60afd15551eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.drop_column('customer_place')
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('customer_place', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
