"""empty message

Revision ID: 50c3dbd07dc2
Revises: c70f0ce68f30
Create Date: 2024-09-01 17:59:13.628013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50c3dbd07dc2'
down_revision = 'c70f0ce68f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_logo', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('company_favicon', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('company_favicon')
        batch_op.drop_column('company_logo')

    # ### end Alembic commands ###
