"""empty message

Revision ID: 6238d732a90f
Revises: cd1b72a6000e
Create Date: 2024-03-09 23:02:28.704832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6238d732a90f'
down_revision = 'cd1b72a6000e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_json', sa.Text(), nullable=True))
        batch_op.alter_column('invoice_date',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_column('final_bill_amount')
        batch_op.drop_column('gst_amount')
        batch_op.drop_column('invoice_product_details')
        batch_op.drop_column('total_amount')
        batch_op.drop_column('sub_total_amount')
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('discount_percentage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_percentage', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('discount_amount', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('sub_total_amount', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('total_amount', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('invoice_product_details', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('gst_amount', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('final_bill_amount', sa.TEXT(), nullable=True))
        batch_op.alter_column('invoice_date',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('invoice_json')

    # ### end Alembic commands ###
