"""empty message

Revision ID: 9aac83ab3e14
Revises: ab93d8b34b38
Create Date: 2024-03-01 22:08:26.189076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aac83ab3e14'
down_revision = 'ab93d8b34b38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_no', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.Text(), nullable=True),
    sa.Column('customer_place', sa.Text(), nullable=True),
    sa.Column('invoice_date', sa.DateTime(), nullable=True),
    sa.Column('invoice_product_details', sa.Text(), nullable=True),
    sa.Column('sub_total_amount', sa.Text(), nullable=True),
    sa.Column('discount_percentage', sa.Text(), nullable=True),
    sa.Column('discount_amount', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Text(), nullable=True),
    sa.Column('gst_amount', sa.Text(), nullable=True),
    sa.Column('final_bill_amount', sa.Text(), nullable=True),
    sa.Column('date_time_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoices')
    # ### end Alembic commands ###
