"""empty message

Revision ID: ab93d8b34b38
Revises: 8e4e6a8bec69
Create Date: 2024-03-01 22:08:00.408171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab93d8b34b38'
down_revision = '8e4e6a8bec69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoices')
    op.drop_table('_alembic_tmp_invoices')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_invoices',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('invoice_no', sa.INTEGER(), nullable=True),
    sa.Column('customer_name', sa.TEXT(), nullable=True),
    sa.Column('customer_place', sa.TEXT(), nullable=True),
    sa.Column('invoice_date', sa.DATETIME(), nullable=True),
    sa.Column('invoice_product_details', sa.TEXT(), nullable=True),
    sa.Column('sub_total_amount', sa.TEXT(), nullable=True),
    sa.Column('final_bill_amount', sa.TEXT(), nullable=True),
    sa.Column('date_time_added', sa.DATETIME(), nullable=True),
    sa.Column('discount_percentage', sa.TEXT(), nullable=True),
    sa.Column('discount_amount', sa.TEXT(), nullable=True),
    sa.Column('total_amount', sa.TEXT(), nullable=True),
    sa.Column('gst_amount', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_no', name='unique_invoice_no')
    )
    op.create_table('invoices',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('invoice_no', sa.INTEGER(), nullable=True),
    sa.Column('customer_name', sa.TEXT(), nullable=True),
    sa.Column('customer_place', sa.TEXT(), nullable=True),
    sa.Column('invoice_date', sa.DATETIME(), nullable=True),
    sa.Column('invoice_product_details', sa.TEXT(), nullable=True),
    sa.Column('sub_total_amount', sa.TEXT(), nullable=True),
    sa.Column('final_bill_amount', sa.TEXT(), nullable=True),
    sa.Column('date_time_added', sa.DATETIME(), nullable=True),
    sa.Column('discount_percentage', sa.TEXT(), nullable=True),
    sa.Column('discount_amount', sa.TEXT(), nullable=True),
    sa.Column('total_amount', sa.TEXT(), nullable=True),
    sa.Column('gst_amount', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
