"""empty message

Revision ID: afc2794b27b4
Revises: dce09bc23244
Create Date: 2024-09-28 19:44:02.502281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afc2794b27b4'
down_revision = 'dce09bc23244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('mobile_no',
               existing_type=sa.BIGINT(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('mobile_no',
               existing_type=sa.Text(),
               type_=sa.BIGINT(),
               existing_nullable=True)

    # ### end Alembic commands ###
